### ISSUE TITLE
spelling issue

### ISSUE THREAD

**Issue by taojintianxia** [xuwujing/java-study#1]
java-study 是本人学习Java过程中记录的一些代码！从Java基础的数据类型、jdk1.8的Lambda、Stream和日期的使用、 IO流、数据集合、多线程使用、并发编程、**23中**设计模式示例代码、常用的工具类， 以及一些常用框架，netty、mina、springboot、kafka、storm、zookeeper、redis、elasticsearch、hbase、hive等等。

无意中看到就随手提了个issue

**Comment by xuwujing** [comment]
@taojintianxia 谢谢提醒
